version: '3.8'

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: senha_segura
      POSTGRES_USER: usuario_postgres
      POSTGRES_DB: rails_production

  web:
    build: .
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://usuario_postgres:senha_segura@db/rails_production

volumes:
  postgres_data:
